OPTION_GROUPS = {
    "Career Options": {
        "avg_career": "AVG Career",
        "era_career": "ERA Career",
        "wins_career": "Wins Career",
        "k_career": "K Career",
        "hits_career": "Hits Career",
        "hr_career": "HR Career",
        "save_career": "Save Career",
        "war_career": "WAR Career",
    },
    "Season Options": {
        "avg_season": "AVG Season",
        "era_season": "ERA Season",
        "hr_season": "HR Season",
        "win_season": "Win Season",
        "rbi_season": "RBI Season",
        "run_season": "Run Season",
        "hits_season": "Hits Season",
        "k_season": "K Season",
        "hr_sb_season": "HR / SB Season",
        "save_season": "Save Season",
        "war_season": "WAR Season",
    },
    "Team Options": {"played_for_team": "Played For Team"},
    "Position Options": {
        "DH": "Designated Hitter",
        "P": "Pitched",
        "C": "Played Catcher",
        "CF": "Played Center Field",
        "1B": "Played First Base",
        "LF": "Played Left Field",
        "OF": "Played Outfield",
        "RF": "Played Right Field",
        "2B": "Played Second Base",
        "SS": "Played Shortstop",
        "3B": "Played Third Base",
    },
    "Miscellaneous": {
        "All Star": "Played in an All Star game",
        "Born Outside US": "Born Outside US 50 States and DC",
        "First Round Draft Pick": "First Round Draft Pick",
        "Hall of Fame": "Inducted into the Hall of Fame",
        "MVP": "Regular Season MVP",
        "Only One Team": "Played for Only One Team",
        "No Hitter": "Threw a No‑Hitter",
        "WS Champ": "World Series Champ",
        "ALCS MVP": "ALCS MVP",
        "All-Star Game MVP": "All-Star Game MVP",
        "Babe Ruth Award": "Babe Ruth Award",
        "Baseball Magazine All-Star": "Baseball Magazine All-Star",
        "BBWAA Manager of the Year": "BBWAA Manager of the Year",
        "Branch Rickey Award": "Branch Rickey Award",
        "Comeback Player of the Year": "Comeback Player of the Year",
        "Cy Young Award": "Cy Young Award",
        "Gold Glove": "Gold Glove",
        "Hank Aaron Award": "Hank Aaron Award",
        "Hutch Award": "Hutch Award",
        "Lou Gehrig Memorial Award": "Lou Gehrig Memorial Award",
        "Most Valuable Player": "Most Valuable Player",
        "NLCS MVP": "NLCS MVP",
        "Outstanding DH Award": "Outstanding DH Award",
        "Pitching Triple Crown": "Pitching Triple Crown",
        "Platinum Glove": "Platinum Glove",
        "Reliever of the Year Award": "Reliever of the Year Award",
        "Roberto Clemente Award": "Roberto Clemente Award",
        "Rolaids Relief Man Award": "Rolaids Relief Man Award",
        "Rookie of the Year": "Rookie of the Year",
        "Rookie of the Year Award": "Rookie of the Year Award",
        "Silver Slugger": "Silver Slugger",
        "Triple Crown": "Triple Crown",
        "TSN All-Star": "TSN All-Star",
        "TSN Fireman of the Year": "TSN Fireman of the Year",
        "TSN Guide MVP": "TSN Guide MVP",
        "TSN Major League Player of the Year": "TSN Major League Player of the Year",
        "TSN Manager of the Year": "TSN Manager of the Year",
        "TSN Pitcher of the Year": "TSN Pitcher of the Year",
        "TSN Player of the Year": "TSN Player of the Year",
        "TSN Reliever of the Year": "TSN Reliever of the Year",
        "World Series MVP": "World Series MVP",
    },
}

TEAM_MAPPINGS = {
    "ALT": "Altoona Mountain City",
    "ANA": "Anaheim Angels",
    "ARI": "Arizona Diamondbacks",
    "ATL": "Atlanta Braves",
    "BAL": "Baltimore Orioles",
    "BFN": "Buffalo Bisons",
    "BFP": "Buffalo Bisons",
    "BL1": "Baltimore Canaries",
    "BL2": "Baltimore Orioles",
    "BL3": "Baltimore Orioles",
    "BL4": "Baltimore Marylands",
    "BLA": "Baltimore Orioles",
    "BLF": "Baltimore Terrapins",
    "BLN": "Baltimore Orioles",
    "BLU": "Baltimore Monumentals",
    "BOS": "Boston Red Sox",
    "BR1": "Brooklyn Eckfords",
    "BR2": "Brooklyn Atlantics",
    "BR3": "Brooklyn Bridegrooms",
    "BR4": "Brooklyn Gladiators",
    "BRF": "Brooklyn Tip-Tops",
    "BRO": "Brooklyn Dodgers",
    "BRP": "Brooklyn Ward's Wonders",
    "BS1": "Boston Red Stockings",
    "BS2": "Boston Reds",
    "BSN": "Boston Braves",
    "BSP": "Boston Reds",
    "BSU": "Boston Reds",
    "BUF": "Buffalo Blues",
    "CAL": "California Angels",
    "CH1": "Chicago White Stockings",
    "CH2": "Chicago White Stockings",
    "CHA": "Chicago White Sox",
    "CHF": "Chicago Whales",
    "CHN": "Chicago Cubs",
    "CHP": "Chicago Pirates",
    "CHU": "Chicago/Pittsburgh (Union League)",
    "CIN": "Cincinnati Reds",
    "CL1": "Cleveland Forest Citys",
    "CL2": "Cleveland Blues",
    "CL3": "Cleveland Blues",
    "CL4": "Cleveland Spiders",
    "CL5": "Columbus Buckeyes",
    "CL6": "Columbus Solons",
    "CLE": "Cleveland Guardians",
    "CLP": "Cleveland Infants",
    "CN1": "Cincinnati Reds",
    "CN2": "Cincinnati Red Stockings",
    "CN3": "Cincinnati Kelly's Killers",
    "CNU": "Cincinnati Outlaw Reds",
    "COL": "Colorado Rockies",
    "DET": "Detroit Tigers",
    "DTN": "Detroit Wolverines",
    "ELI": "Elizabeth Resolutes",
    "FLO": "Florida Marlins",
    "FW1": "Fort Wayne Kekiongas",
    "HAR": "Hartford Dark Blues",
    "HOU": "Houston Astros",
    "HR1": "Hartford Dark Blues",
    "IN1": "Indianapolis Blues",
    "IN2": "Indianapolis Hoosiers",
    "IN3": "Indianapolis Hoosiers",
    "IND": "Indianapolis Hoosiers",
    "KC1": "Kansas City Athletics",
    "KC2": "Kansas City Cowboys",
    "KCA": "Kansas City Royals",
    "KCF": "Kansas City Packers",
    "KCN": "Kansas City Cowboys",
    "KCU": "Kansas City Cowboys",
    "KEO": "Keokuk Westerns",
    "LAA": "Los Angeles Angels",
    "LAN": "Los Angeles Dodgers",
    "LS1": "Louisville Grays",
    "LS2": "Louisville Colonels",
    "LS3": "Louisville Colonels",
    "MIA": "Miami Marlins",
    "MID": "Middletown Mansfields",
    "MIL": "Milwaukee Brewers",
    "MIN": "Minnesota Twins",
    "ML1": "Milwaukee Braves",
    "ML2": "Milwaukee Grays",
    "ML3": "Milwaukee Brewers",
    "ML4": "Milwaukee Brewers",
    "MLA": "Milwaukee Brewers",
    "MLU": "Milwaukee Brewers",
    "MON": "Montreal Expos",
    "NEW": "Newark Pepper",
    "NH1": "New Haven Elm Citys",
    "NY1": "New York Giants",
    "NY2": "New York Mutuals",
    "NY3": "New York Mutuals",
    "NY4": "New York Metropolitans",
    "NYA": "New York Yankees",
    "NYN": "New York Mets",
    "NYP": "New York Giants",
    "OAK": "Oakland Athletics",
    "PH1": "Philadelphia Athletics",
    "PH2": "Philadelphia Whites",
    "PH3": "Philadelphia Centennials",
    "PH4": "Philadelphia Athletics",
    "PHA": "Philadelphia Athletics",
    "PHI": "Philadelphia Phillies",
    "PHN": "Philadelphia Athletics",
    "PHP": "Philadelphia Athletics",
    "PHU": "Philadelphia Keystones",
    "PIT": "Pittsburgh Pirates",
    "PRO": "Providence Grays",
    "PT1": "Pittsburg Alleghenys",
    "PTF": "Pittsburgh Rebels",
    "PTP": "Pittsburgh Burghers",
    "RC1": "Rockford Forest Citys",
    "RC2": "Rochester Broncos",
    "RIC": "Richmond Virginians",
    "SDN": "San Diego Padres",
    "SE1": "Seattle Pilots",
    "SEA": "Seattle Mariners",
    "SFN": "San Francisco Giants",
    "SL1": "St. Louis Red Stockings",
    "SL2": "St. Louis Brown Stockings",
    "SL3": "St. Louis Brown Stockings",
    "SL4": "St. Louis Browns",
    "SL5": "St. Louis Maroons",
    "SLA": "St. Louis Browns",
    "SLF": "St. Louis Terriers",
    "SLN": "St. Louis Cardinals",
    "SLU": "St. Louis Maroons",
    "SPU": "St. Paul White Caps",
    "SR1": "Syracuse Stars",
    "SR2": "Syracuse Stars",
    "TBA": "Tampa Bay Rays",
    "TEX": "Texas Rangers",
    "TL1": "Toledo Blue Stockings",
    "TL2": "Toledo Maumees",
    "TOR": "Toronto Blue Jays",
    "TRN": "Troy Trojans",
    "TRO": "Troy Haymakers",
    "WAS": "Washington Nationals",
    "WIL": "Wilmington Quicksteps",
    "WOR": "Worcester Ruby Legs",
    "WS1": "Washington Senators",
    "WS2": "Washington Senators",
    "WS3": "Washington Olympics",
    "WS4": "Washington Nationals",
    "WS5": "Washington Blue Legs",
    "WS6": "Washington Nationals",
    "WS7": "Washington Nationals",
    "WS8": "Washington Nationals",
    "WS9": "Washington Statesmen",
    "WSU": "Washington Nationals",
}
