OPTION_GROUPS = {
    "Career Options": {
        "avg_career": "AVG Career",
        "era_career": "ERA Career",
        "wins_career": "Wins Career",
        "k_career": "K Career",
        "hits_career": "Hits Career",
        "hr_career": "HR Career",
        "save_career": "Save Career",
        "war_career": "WAR Career",
    },
    "Season Options": {
        "avg_season": "AVG Season",
        "era_season": "ERA Season",
        "hr_season": "HR Season",
        "win_season": "Win Season",
        "rbi_season": "RBI Season",
        "run_season": "Run Season",
        "hits_season": "Hits Season",
        "k_season": "K Season",
        "hr_sb_season": "HR / SB Season",
        "save_season": "Save Season",
        "war_season": "WAR Season",
    },
    "Team Options": {"played_for_team": "Played For Team"},
    "Position Options": {
        "DH": "Designated Hitter",
        "P": "Pitched",
        "C": "Played Catcher",
        "CF": "Played Center Field",
        "1B": "Played First Base",
        "LF": "Played Left Field",
        "OF": "Played Outfield",
        "RF": "Played Right Field",
        "2B": "Played Second Base",
        "SS": "Played Shortstop",
        "3B": "Played Third Base",
    },
    "Miscellaneous": {
        "All Star": "Played in an All Star game",
        "Born Outside US": "Born Outside US 50 States and DC",
        "First Round Draft Pick": "First Round Draft Pick",
        "Hall of Fame": "Inducted into the Hall of Fame",
        "Only One Team": "Played for Only One Team",
        "No Hitter": "Threw a No‑Hitter",
        "WS Champ": "World Series Champ",
        "ALCS MVP": "ALCS MVP",
        "All-Star Game MVP": "All-Star Game MVP",
        "Babe Ruth Award": "Babe Ruth Award",
        "Baseball Magazine All-Star": "Baseball Magazine All-Star",
        "BBWAA Manager of the Year": "BBWAA Manager of the Year",
        "Branch Rickey Award": "Branch Rickey Award",
        "Comeback Player of the Year": "Comeback Player of the Year",
        "Cy Young Award": "Cy Young Award",
        "Gold Glove": "Gold Glove",
        "Hank Aaron Award": "Hank Aaron Award",
        "Hutch Award": "Hutch Award",
        "Lou Gehrig Memorial Award": "Lou Gehrig Memorial Award",
        "Most Valuable Player": "Most Valuable Player",
        "NLCS MVP": "NLCS MVP",
        "Outstanding DH Award": "Outstanding DH Award",
        "Pitching Triple Crown": "Pitching Triple Crown",
        "Platinum Glove": "Platinum Glove",
        "Reliever of the Year Award": "Reliever of the Year Award",
        "Roberto Clemente Award": "Roberto Clemente Award",
        "Rolaids Relief Man Award": "Rolaids Relief Man Award",
        "Rookie of the Year": "Rookie of the Year",
        "Rookie of the Year Award": "Rookie of the Year Award",
        "Silver Slugger": "Silver Slugger",
        "Triple Crown": "Triple Crown",
        "TSN All-Star": "TSN All-Star",
        "TSN Fireman of the Year": "TSN Fireman of the Year",
        "TSN Guide MVP": "TSN Guide MVP",
        "TSN Major League Player of the Year": "TSN Major League Player of the Year",
        "TSN Manager of the Year": "TSN Manager of the Year",
        "TSN Pitcher of the Year": "TSN Pitcher of the Year",
        "TSN Player of the Year": "TSN Player of the Year",
        "TSN Reliever of the Year": "TSN Reliever of the Year",
        "World Series MVP": "World Series MVP",
    },
}

TEAM_MAPPINGS = [
    "Altoona Mountain City",
    "Anaheim Angels",
    "Arizona Diamondbacks",
    "Atlanta Braves",
    "Baltimore Canaries",
    "Baltimore Marylands",
    "Baltimore Monumentals",
    "Baltimore Orioles",
    "Baltimore Terrapins",
    "Boston Americans",
    "Boston Beaneaters",
    "Boston Bees",
    "Boston Braves",
    "Boston Doves",
    "Boston Red Caps",
    "Boston Red Sox",
    "Boston Red Stockings",
    "Boston Reds",
    "Boston Rustlers",
    "Brooklyn Atlantics",
    "Brooklyn Bridegrooms",
    "Brooklyn Dodgers",
    "Brooklyn Eckfords",
    "Brooklyn Gladiators",
    "Brooklyn Grays",
    "Brooklyn Grooms",
    "Brooklyn Robins",
    "Brooklyn Superbas",
    "Brooklyn Tip-Tops",
    "Brooklyn Ward's Wonders",
    "Buffalo Bisons",
    "Buffalo Blues",
    "Buffalo Buffeds",
    "California Angels",
    "Chicago Chi-Feds",
    "Chicago Colts",
    "Chicago Cubs",
    "Chicago Orphans",
    "Chicago Pirates",
    "Chicago Whales",
    "Chicago White Sox",
    "Chicago White Stockings",
    "Chicago/Pittsburgh (Union League)",
    "Cincinnati Kelly's Killers",
    "Cincinnati Outlaw Reds",
    "Cincinnati Red Stockings",
    "Cincinnati Redlegs",
    "Cincinnati Reds",
    "Cleveland Blues",
    "Cleveland Bronchos",
    "Cleveland Forest Citys",
    "Cleveland Guardians",
    "Cleveland Indians",
    "Cleveland Infants",
    "Cleveland Naps",
    "Cleveland Spiders",
    "Colorado Rockies",
    "Columbus Buckeyes",
    "Columbus Solons",
    "Detroit Tigers",
    "Detroit Wolverines",
    "Elizabeth Resolutes",
    "Florida Marlins",
    "Fort Wayne Kekiongas",
    "Hartford Dark Blues",
    "Houston Astros",
    "Houston Colt .45's",
    "Indianapolis Blues",
    "Indianapolis Hoosiers",
    "Kansas City Athletics",
    "Kansas City Cowboys",
    "Kansas City Packers",
    "Kansas City Royals",
    "Keokuk Westerns",
    "Los Angeles Angels",
    "Los Angeles Angels of Anaheim",
    "Los Angeles Dodgers",
    "Louisville Colonels",
    "Louisville Eclipse",
    "Louisville Grays",
    "Miami Marlins",
    "Middletown Mansfields",
    "Milwaukee Braves",
    "Milwaukee Brewers",
    "Milwaukee Grays",
    "Minnesota Twins",
    "Montreal Expos",
    "New Haven Elm Citys",
    "New York Giants",
    "New York Gothams",
    "New York Highlanders",
    "New York Metropolitans",
    "New York Mets",
    "New York Mutuals",
    "New York Yankees",
    "Newark Pepper",
    "Oakland Athletics",
    "Philadelphia Athletics",
    "Philadelphia Blue Jays",
    "Philadelphia Centennials",
    "Philadelphia Keystones",
    "Philadelphia Phillies",
    "Philadelphia Quakers",
    "Philadelphia Whites",
    "Pittsburg Alleghenys",
    "Pittsburgh Burghers",
    "Pittsburgh Pirates",
    "Pittsburgh Rebels",
    "Providence Grays",
    "Richmond Virginians",
    "Rochester Broncos",
    "Rockford Forest Citys",
    "San Diego Padres",
    "San Francisco Giants",
    "Seattle Mariners",
    "Seattle Pilots",
    "St. Louis Brown Stockings",
    "St. Louis Browns",
    "St. Louis Cardinals",
    "St. Louis Maroons",
    "St. Louis Perfectos",
    "St. Louis Red Stockings",
    "St. Louis Terriers",
    "St. Paul White Caps",
    "Syracuse Stars",
    "Tampa Bay Devil Rays",
    "Tampa Bay Rays",
    "Texas Rangers",
    "Toledo Blue Stockings",
    "Toledo Maumees",
    "Toronto Blue Jays",
    "Troy Haymakers",
    "Troy Trojans",
    "Washington Blue Legs",
    "Washington Nationals",
    "Washington Olympics",
    "Washington Senators",
    "Washington Statesmen",
    "Wilmington Quicksteps",
    "Worcester Ruby Legs",
]

TEAM_MAPPINGS = {team: team for team in TEAM_MAPPINGS}
